name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: .NET build
        working-directory: DotnetTemplate.Web
        run: dotnet build

      - name: npm install
        working-directory: DotnetTemplate.Web
        run: npm install

      - name: npm lint
        working-directory: DotnetTemplate.Web
        run: npm run lint

      - name: npm test
        working-directory: DotnetTemplate.Web
        run: npm test

      - name: .NET test
        run: dotnet test

    